### ISSUE TITLE
Curriculum slide out of sync with official curriculum

### ISSUE THREAD

**Issue by rwxrob** [bmuschko/ckad-crash-course#10]
https://github.com/cncf/curriculum/blob/master/CKAD_Curriculum_v1.23.pdf

**Comment by bmuschko** [comment]
Thanks for the nudge. I am well aware of those changes and am planning to make the relevant changes soon. If you look at the detail, you will find that the new curriculum isn't that different. I added links to the new topics on slide 8 in the PDF file.

Side note: I already talked to O'Reilly Media about this and we are planning to update the CKAD study guide book the new curriculum with a second edition.

**Comment by bmuschko** [comment]
I just pushed an updated slide deck that covers the new curriculum.
