### ISSUE TITLE
Exercise 30 ingress solution doesn't work on M1 Mac

### ISSUE THREAD

**Issue by matt4biz** [bmuschko/ckad-crash-course#22]
Exercise 30 in `exercises/30-ingress/solution/solution.md` shows a step adding the Minikube IP (here 192.168.64.38)
to `/etc/hosts` together with the ingress hostname.

On an M1 Mac [Apple Silicon] this doesn't work. The `localhost` IP address (127.0.0.1) should be used instead; when I made this change, things worked as shown (with the Minikube tunnel running also).

However, I don't think `k get ingress` ever showed `localhost` in the address column.

See https://stackoverflow.com/questions/58561682/minikube-with-ingress-example-not-working; look at point 7 in the highest-scoring answer and its comments. (I don't know why they show enabling MK's `ingress-dns` add-on; I didn't need to do that.)

**Comment by bmuschko** [comment]
Thanks! I clarified the solution with commit https://github.com/bmuschko/ckad-crash-course/commit/4266c7f1ce5da0a5ba5cbbe26b6a991059b25ee2.
